name: magic_remove
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  image_picker: ^1.1.2
  gal: ^2.2.0
  path_provider: ^2.1.4
  carousel_slider: ^5.0.0
  lottie: ^3.1.2
  google_mobile_ads: ^6.0.0
  flutter_painter_v2: ^2.1.0
  provider: ^6.1.2
  go_router: ^14.2.0
  shared_preferences: ^2.3.2
  http: ^1.2.2
  share_plus: 7.2.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
